name: flutter_credit_card
description: A Credit Card widget package with support of entering card details, and animations like card flip
  and float.
version: 4.0.1
homepage: https://github.com/simformsolutions/flutter_credit_card
issue_tracker: https://github.com/simformsolutions/flutter_credit_card/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    androidPackage: com.simform.flutter_credit_card  # This should match the package name
    mainClass: com.simform.flutter_credit_card.FlutterCreditCardPlugin  # This should match the plugin class location

  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf

